name: build vllm

on:
  workflow_dispatch:  # 手动触发

jobs:
  start-ssh-server:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
            
      - name: 安装 davfs2
        run: sudo apt update && sudo apt install -y davfs2

      - name: 创建挂载目录
        run: sudo mkdir -p /mnt/share

      - name: 配置凭据文件（root 访问）
        run: |
          echo "https://app.koofr.net/dav/Koofr/ ${{ secrets.KOOFR_USERNAME }} ${{ secrets.KOOFR_PASSWORD }}" | sudo tee /etc/davfs2/secrets > /dev/null
          sudo chmod 600 /etc/davfs2/secrets
      - name: 允许 root 访问 WebDAV
        run: echo "use_locks 0" | sudo tee -a /etc/davfs2/davfs2.conf > /dev/null

      - name: 以 root 挂载 Koofr
        run: sudo mount -t davfs https://app.koofr.net/dav/Koofr/ /mnt/share

      - name: 输出 SSH 连接方式
        run: |
          sudo rm -rf /usr/local/lib/android/sdk
          sudo rm -rf /opt/hostedtoolcache
          git clone https://github.com/vllm-project/vllm.git
          cd vllm
          git checkout c6ed93860fa8338bf7e4dfcce0040046a2f0df48
          sed -i 's/name = "vllm"/name = "lazyllm-vllm"/' pyproject.toml
      - name: Install CUDA ${{ matrix.cuda-version }}
        run: |
          cd vllm
          bash -x .github/workflows/scripts/cuda-install.sh 12.4 ubuntu-22.04
      - name: Build wheel
        shell: bash
        env:
          CMAKE_BUILD_TYPE: Release # do not compile with debug symbol to reduce wheel size
        run: |
          cd vllm
          echo 'sleep 1' > tools/check_repo.sh
          sed -i '9d' .github/workflows/scripts/build.sh
          sed -i '21 i python3 -m pip install setuptools==69.3.0' .github/workflows/scripts/build.sh
          bash -x .github/workflows/scripts/build.sh 3 12.4
          sudo cp -a dist /mnt/share/
          wheel_name=$(find dist -name "*whl" -print0 | xargs -0 -n 1 basename)
          asset_name=${wheel_name//"linux"/"manylinux1"}
          echo "wheel_name=${wheel_name}" >> "$GITHUB_ENV"
          echo "asset_name=${asset_name}" >> "$GITHUB_ENV"
          sleep 1h
