name: Dockerhub 2 Aliyun

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: '源镜像信息 (e.g., registry/source:tag)'
        required: true
        type: string
      target_image:
        description: '目标阿里云镜像信息 (e.g., registry/target:tag)'
        required: true
        type: string

jobs:
  copy-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout (required by GitHub Actions even if not used)
        uses: actions/checkout@v4

      - name: 扩大空间
        run: |
          sudo rm -rf /usr/local/lib/android/sdk &
          sudo rm -rf /opt/hostedtoolcache &
          
      - name: Pull source image
        run: |
          docker pull "${{ github.event.inputs.source_image }}"

      - name: Tag to target image
        run: |
          docker tag "${{ github.event.inputs.source_image }}" "${{ github.event.inputs.target_image }}"
          
      - name: aliyun registry login
        env:
          DOCKER_USER: ${{ secrets.ALIYUN_DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
          
        run: |
          echo "$DOCKER_PASSWORD" | docker login registry.cn-hangzhou.aliyuncs.com --username "$DOCKER_USER" --password-stdin
          
      - name: Push target image
        run: |
          docker push "${{ github.event.inputs.target_image }}"

      - name: Remove local images
        run: |
          docker rmi "${{ github.event.inputs.source_image }}" "${{ github.event.inputs.target_image }}"
